# https://taskfile.dev
version: "3"
tasks:
  default: mix test

  pub:
    desc: publish package
    cmds:
      - mix hex.publish --yes --replace
  # mix hex.publish package
  pub-docs: mix hex.publish docs --yes

  mk-lib: mix new . --module HelloLibary --app hello_libary --sup
