# https://taskfile.dev
version: "3"
tasks:
  default: mix test

  pub:
    desc: publish package
    cmds:
      - mix hex.publish --yes

  mk-lib: mix new . --module HelloLibary --app hello_libary --sup
