# https://taskfile.dev
version: '3'
tasks:
  default: mix test
  
  pub:
    desc: publish package
    cmds:
    - mix hex.publish
    
  gen-docs:
    desc: generate docs by help ex_doc
    cmds:
    - mix docs

  setup:
    desc: setup base code
    cmds:
    # - mkdir hello-elixir-libary && cd hello-elixir-libary
    - mix new . --module Hello --app hello_libary --sup